/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package Rule;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class RuleMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4933928356128317157L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RuleMessage\",\"namespace\":\"Rule\",\"fields\":[{\"name\":\"station\",\"type\":\"string\"},{\"name\":\"model\",\"type\":\"string\"},{\"name\":\"io\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":\"long\"},{\"name\":\"value\",\"type\":\"float\"},{\"name\":\"connection\",\"type\":\"boolean\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RuleMessage> ENCODER =
      new BinaryMessageEncoder<RuleMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RuleMessage> DECODER =
      new BinaryMessageDecoder<RuleMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<RuleMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<RuleMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RuleMessage>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this RuleMessage to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a RuleMessage from a ByteBuffer. */
  public static RuleMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence station;
  @Deprecated public java.lang.CharSequence model;
  @Deprecated public java.lang.CharSequence io;
  @Deprecated public long timestamp;
  @Deprecated public float value;
  @Deprecated public boolean connection;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RuleMessage() {}

  /**
   * All-args constructor.
   * @param station The new value for station
   * @param model The new value for model
   * @param io The new value for io
   * @param timestamp The new value for timestamp
   * @param value The new value for value
   * @param connection The new value for connection
   */
  public RuleMessage(java.lang.CharSequence station, java.lang.CharSequence model, java.lang.CharSequence io, java.lang.Long timestamp, java.lang.Float value, java.lang.Boolean connection) {
    this.station = station;
    this.model = model;
    this.io = io;
    this.timestamp = timestamp;
    this.value = value;
    this.connection = connection;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return station;
    case 1: return model;
    case 2: return io;
    case 3: return timestamp;
    case 4: return value;
    case 5: return connection;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: station = (java.lang.CharSequence)value$; break;
    case 1: model = (java.lang.CharSequence)value$; break;
    case 2: io = (java.lang.CharSequence)value$; break;
    case 3: timestamp = (java.lang.Long)value$; break;
    case 4: value = (java.lang.Float)value$; break;
    case 5: connection = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'station' field.
   * @return The value of the 'station' field.
   */
  public java.lang.CharSequence getStation() {
    return station;
  }

  /**
   * Sets the value of the 'station' field.
   * @param value the value to set.
   */
  public void setStation(java.lang.CharSequence value) {
    this.station = value;
  }

  /**
   * Gets the value of the 'model' field.
   * @return The value of the 'model' field.
   */
  public java.lang.CharSequence getModel() {
    return model;
  }

  /**
   * Sets the value of the 'model' field.
   * @param value the value to set.
   */
  public void setModel(java.lang.CharSequence value) {
    this.model = value;
  }

  /**
   * Gets the value of the 'io' field.
   * @return The value of the 'io' field.
   */
  public java.lang.CharSequence getIo() {
    return io;
  }

  /**
   * Sets the value of the 'io' field.
   * @param value the value to set.
   */
  public void setIo(java.lang.CharSequence value) {
    this.io = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.lang.Long getTimestamp() {
    return timestamp;
  }

  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.lang.Long value) {
    this.timestamp = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return The value of the 'value' field.
   */
  public java.lang.Float getValue() {
    return value;
  }

  /**
   * Sets the value of the 'value' field.
   * @param value the value to set.
   */
  public void setValue(java.lang.Float value) {
    this.value = value;
  }

  /**
   * Gets the value of the 'connection' field.
   * @return The value of the 'connection' field.
   */
  public java.lang.Boolean getConnection() {
    return connection;
  }

  /**
   * Sets the value of the 'connection' field.
   * @param value the value to set.
   */
  public void setConnection(java.lang.Boolean value) {
    this.connection = value;
  }

  /**
   * Creates a new RuleMessage RecordBuilder.
   * @return A new RuleMessage RecordBuilder
   */
  public static Rule.RuleMessage.Builder newBuilder() {
    return new Rule.RuleMessage.Builder();
  }

  /**
   * Creates a new RuleMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RuleMessage RecordBuilder
   */
  public static Rule.RuleMessage.Builder newBuilder(Rule.RuleMessage.Builder other) {
    return new Rule.RuleMessage.Builder(other);
  }

  /**
   * Creates a new RuleMessage RecordBuilder by copying an existing RuleMessage instance.
   * @param other The existing instance to copy.
   * @return A new RuleMessage RecordBuilder
   */
  public static Rule.RuleMessage.Builder newBuilder(Rule.RuleMessage other) {
    return new Rule.RuleMessage.Builder(other);
  }

  /**
   * RecordBuilder for RuleMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RuleMessage>
    implements org.apache.avro.data.RecordBuilder<RuleMessage> {

    private java.lang.CharSequence station;
    private java.lang.CharSequence model;
    private java.lang.CharSequence io;
    private long timestamp;
    private float value;
    private boolean connection;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(Rule.RuleMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.station)) {
        this.station = data().deepCopy(fields()[0].schema(), other.station);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.model)) {
        this.model = data().deepCopy(fields()[1].schema(), other.model);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.io)) {
        this.io = data().deepCopy(fields()[2].schema(), other.io);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.value)) {
        this.value = data().deepCopy(fields()[4].schema(), other.value);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.connection)) {
        this.connection = data().deepCopy(fields()[5].schema(), other.connection);
        fieldSetFlags()[5] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing RuleMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(Rule.RuleMessage other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.station)) {
        this.station = data().deepCopy(fields()[0].schema(), other.station);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.model)) {
        this.model = data().deepCopy(fields()[1].schema(), other.model);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.io)) {
        this.io = data().deepCopy(fields()[2].schema(), other.io);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.value)) {
        this.value = data().deepCopy(fields()[4].schema(), other.value);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.connection)) {
        this.connection = data().deepCopy(fields()[5].schema(), other.connection);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'station' field.
      * @return The value.
      */
    public java.lang.CharSequence getStation() {
      return station;
    }

    /**
      * Sets the value of the 'station' field.
      * @param value The value of 'station'.
      * @return This builder.
      */
    public Rule.RuleMessage.Builder setStation(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.station = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'station' field has been set.
      * @return True if the 'station' field has been set, false otherwise.
      */
    public boolean hasStation() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'station' field.
      * @return This builder.
      */
    public Rule.RuleMessage.Builder clearStation() {
      station = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'model' field.
      * @return The value.
      */
    public java.lang.CharSequence getModel() {
      return model;
    }

    /**
      * Sets the value of the 'model' field.
      * @param value The value of 'model'.
      * @return This builder.
      */
    public Rule.RuleMessage.Builder setModel(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.model = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'model' field has been set.
      * @return True if the 'model' field has been set, false otherwise.
      */
    public boolean hasModel() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'model' field.
      * @return This builder.
      */
    public Rule.RuleMessage.Builder clearModel() {
      model = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'io' field.
      * @return The value.
      */
    public java.lang.CharSequence getIo() {
      return io;
    }

    /**
      * Sets the value of the 'io' field.
      * @param value The value of 'io'.
      * @return This builder.
      */
    public Rule.RuleMessage.Builder setIo(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.io = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'io' field has been set.
      * @return True if the 'io' field has been set, false otherwise.
      */
    public boolean hasIo() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'io' field.
      * @return This builder.
      */
    public Rule.RuleMessage.Builder clearIo() {
      io = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.lang.Long getTimestamp() {
      return timestamp;
    }

    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public Rule.RuleMessage.Builder setTimestamp(long value) {
      validate(fields()[3], value);
      this.timestamp = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public Rule.RuleMessage.Builder clearTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * @return The value.
      */
    public java.lang.Float getValue() {
      return value;
    }

    /**
      * Sets the value of the 'value' field.
      * @param value The value of 'value'.
      * @return This builder.
      */
    public Rule.RuleMessage.Builder setValue(float value) {
      validate(fields()[4], value);
      this.value = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'value' field.
      * @return This builder.
      */
    public Rule.RuleMessage.Builder clearValue() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'connection' field.
      * @return The value.
      */
    public java.lang.Boolean getConnection() {
      return connection;
    }

    /**
      * Sets the value of the 'connection' field.
      * @param value The value of 'connection'.
      * @return This builder.
      */
    public Rule.RuleMessage.Builder setConnection(boolean value) {
      validate(fields()[5], value);
      this.connection = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'connection' field has been set.
      * @return True if the 'connection' field has been set, false otherwise.
      */
    public boolean hasConnection() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'connection' field.
      * @return This builder.
      */
    public Rule.RuleMessage.Builder clearConnection() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RuleMessage build() {
      try {
        RuleMessage record = new RuleMessage();
        record.station = fieldSetFlags()[0] ? this.station : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.model = fieldSetFlags()[1] ? this.model : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.io = fieldSetFlags()[2] ? this.io : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.timestamp = fieldSetFlags()[3] ? this.timestamp : (java.lang.Long) defaultValue(fields()[3]);
        record.value = fieldSetFlags()[4] ? this.value : (java.lang.Float) defaultValue(fields()[4]);
        record.connection = fieldSetFlags()[5] ? this.connection : (java.lang.Boolean) defaultValue(fields()[5]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RuleMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<RuleMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RuleMessage>
    READER$ = (org.apache.avro.io.DatumReader<RuleMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
